### 1. Test Api Users
### create data users (POST)
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
  "name": "Siti Wulandari",
  "email": "sitiwulandari@gmail.com",
  "password": "sitiw020102",
  "profile": {
    "identity_type": "KTP",
    "identity_number": "187115526637723",
    "address": "Jln.coklat Gg.pemancar 3 No.2 Bengkulu"
  }
}

### get all users
GET http://localhost:3000/api/v1/users

### get detail users by: id
GET http://localhost:3000/api/v1/users/6


### get data users with pagination
GET http://localhost:3000/api/v1/users?limit=2&page=1

### Update data users by: id
PUT http://localhost:3000/api/v1/users/5
Content-Type: application/json

{
  "name": "Wanto Pujianto",
  "email": "wantopj02@gmail.com",
  "password": "wantobdl020102"
}

### delete data users by: id
DELETE http://localhost:3000/api/v1/users/2

### 2. Test Api Accounts
### create data accounts (POST)
POST http://localhost:3000/api/v1/accounts
Content-Type: application/json

{
    "user_id": 6,
    "bank_name": "Bank BRI",
    "bank_account_number": "897829992",
    "balance": 1500000
}

### get all accounts
GET http://localhost:3000/api/v1/accounts

### get detail accounts by: id
GET http://localhost:3000/api/v1/accounts/2


### get data accounts with pagination
GET http://localhost:3000/api/v1/accounts?limit=2&page=1

### update data accounts
PUT http://localhost:3000/api/v1/accounts/5
Content-Type: application/json

{
    "user_id": 5,
    "bank_name": "Bank BRI",
    "bank_account_number": "627726627",
    "balance": 5350000
}

### delete accounts by: id
DELETE http://localhost:3000/api/v1/accounts/5


### 3. Transactions

### Create Data Transactions
POST http://localhost:3000/api/v1/transactions
Content-Type: application/json

{
  "source_account_id": 3,
  "destination_account_id": 5,
  "amount": 490000
}

### get data all transactions
GET http://localhost:3000/api/v1/transactions

### get data by paginations
GET http://localhost:3000/api/v1/transactions?limit=2&page=1

### get detail data transactions by: id
GET http://localhost:3000/api/v1/transactions/2


